### ISSUE TITLE
Cleanup: Remove "deployment awareness" from the code

### ISSUE THREAD

**Issue by HaraldJoerg** [act-psgi/Act#23]
In some places, the code covers up for different deployment paths:

- Starting from ACTHOME (traditional and act-starter-debian) _or_ ACT_HOME (docker).  The docs only have ACTHOME, the error message if neither is set only mentions ACT_HOME.
- Loading conference configs from actdocs/$conference/conf/act.ini (traditional and act-starter-debian) _and_ conferences/$conference/actdocs/ (docker).
- The database names per act.ini templates are actwiki and acttest (traditional and act-starter-debian) resp. act_wiki and act_test (docker)

This is messy and no fun for troubleshooting.  Both the Act codebase and the deployment methods should follow one unambiguous specifications where things are.

**Comment by waterkip** [comment]
+1 I agree with this. For me the deployment awareness is the opinionated testsuite. You need to configure act before you can test it. You can not validate the code is working prior to configuring it. The basedir of act, it shouldn't matter, we should be able to tell act to load a config found at a particular path and let the software deal with it. ACTHOME needs to be set for testing. It then assumes a test database. The deployment is very tightly nit to the code which hinders other setups.

It shouldn't matter what you configure, we should just take the configuration file at face value and work with that.

If we continue to use environment variables, I would prefer `ACT_XXX` over `ACTXXX`, it is a bit more readable and sort of namespaced. This is also used for Postgres, `POSTGRES_USER` and not `POSTGRESUSER` or Minio: `MINIO_SECRET_KEY` vs `MINIOSECRETKEY`.
