### ISSUE TITLE
document the minimal required docker/docker-compose version

### ISSUE THREAD

**Issue by ufobat** [act-psgi/Act#34]
Does it make sense to make the `version: '3.6'` of `docker-compose.yml` as small as possible? I am assuming that this makes our docker setup run on older docker nistallations. (e.g. on ubuntu bionic with the package docker.io)

**Comment by HaraldJoerg** [comment]
This makes sense to reduce the barrier for developers who want to go the easy way to install docker by using their distribution's package manager.  The current LTS version of Ubuntu (18.04 aka Bionic Beaver) including updates provide Docker version  19.03.6 and
docker-compose version 1.17.1.  This works fine if the format of the docker-compose.yml file is downgraded to 3.3, so I'd declare those the minimum supported versions for now.
