### ISSUE TITLE
make DB connection fork save

### ISSUE THREAD

**Issue by domm** [act-psgi/Act#6]
The current DB connection does not work after a fork, which makes it impossible to run the app via e.g. Starman.

Maybe the easiest way would be to use DBIx::Connector?

**Comment by HaraldJoerg** [comment]
Amazingly enough, as the stacktrace shows, the error happens in the only connection which uses DBIx::Connector - and which wasn't present in the stage1 / evolution branches until recently.
This gave the clue... PR upcoming.

BTW: The reason that it works for the old branches without DBIx::Connector is that they connect to the database for every single request - i.e. after forking - while the session management is set up when building the app.

**Comment by domm** [comment]
btw, I tried running Act with this patch on a VM with Starman, and it does in fact work :-)
