### ISSUE TITLE
only one act.ini

### ISSUE THREAD

**Issue by domm** [act-psgi/Act#8]
It seems we currently have two or three act.inis:

* `eg/conf/act.ini`
* `etc/act.ini.dist`
* https://github.com/act-psgi/act-starter-debian/blob/master/act.ini.tt

This makes it rather hard to add/document/clean up config entries.

Maybe we can find a way to only have **one** act.ini template in the repo. Whoever runs an instance will have to adapt act.ini anyway, so it does not have to work out of the box.

The various "installers" (docker-compose, act-starter-debian) could of course mangle the example act.ini to match their respective needs

**Comment by waterkip** [comment]
The act.ini.dist is shipped and used by ./dev-bin/generate-config.sh to then create an act.ini that can be tweaked. Act.ini is excluded in the .gitignore, act.ini.dist is not. .dist is NOT used in any other way.

IMO act.ini.dist should be a docker-start-your-engines configuration file that can be used for first use and tweaked by a user. It can be a template for bare metal instances, but configuration options should be explained in the .dist or elsewhere. Perhaps the .dist is the best place? It is version controlled and limits having to duplicate the documenation.

**Comment by HaraldJoerg** [comment]
The configuration items in the global act.ini are documented at https://github.com/act-psgi/Act/blob/master/lib/Act/Manual/Provider/Configuration.pod, (https://act-test.plix.at/manual/Manual/Provider/Configuration.html) and would in my opinion be the best place to describe the superset of configuration options, and maybe there ENV counterparts, which are evaluated by Act.
